{
 "title": "Core Monitor",
 "time": { "from": "now-30m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "gocore_address",
    "label": "gocore_address",
    "query": "from(bucket: \"my-bucket\")\n// Give range of start and stop as per your usecase\n|> range (start: v.timeRangeStart, stop: v.timeRangeStop)\n|> filter(fn:(r) => r._measurement == \"gocore_node\")\n|> pivot(rowKey:[\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n|> group()\n|> distinct(column: \"host\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Current Block",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "gocore_block",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gocore_node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gocore_block\")\n  |> filter(fn: (r) => r.host == \"${gocore_address}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 4, "y": 0 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "gocore_block_transactions",
     "legendFormat": "Transactions",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gocore_node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gocore_block_transactions\")\n  |> filter(fn: (r) => r.host == \"${gocore_address}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "XCB Transfers",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gocore_core_transfers",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gocore_node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gocore_core_transfers\")\n  |> filter(fn: (r) => r.host == \"${gocore_address}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Pending",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 22, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gocore_pending_transactions",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gocore_node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gocore_pending_transactions\")\n  |> filter(fn: (r) => r.host == \"${gocore_address}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "XCB Value",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gocore_block_value",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gocore_node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gocore_block_value\")\n  |> filter(fn: (r) => r.host == \"${gocore_address}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Energy Price (nucle)",
   "type": "graph",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gocore_energy_price / 1000000000",
     "legendFormat": "Energy Price",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gocore_node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gocore_energy_price\")\n  |> filter(fn: (r) => r.host == \"${gocore_address}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({\n      r with\n      _value: r._value / 1000000000\n    })\n  )"
    }
   ]
  },
  {
   "title": "Energy Price",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gocore_energy_price / 1000000000",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gocore_node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gocore_energy_price\")\n  |> filter(fn: (r) => r.host == \"${gocore_address}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({\n      r with\n      _value: r._value / 1000000000\n    })\n  )"
    }
   ]
  },
  {
   "title": "Since Last Block",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gocore_seconds_last_block",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gocore_node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gocore_seconds_last_block\")\n  |> filter(fn: (r) => r.host == \"${gocore_address}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "XCB Transfers",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 4, "y": 7 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "gocore_core_transfers",
     "legendFormat": "XCB Transfers",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gocore_node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gocore_core_transfers\")\n  |> filter(fn: (r) => r.host == \"${gocore_address}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Contracts Created",
   "type": "graph",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 8 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "gocore_contracts_created",
     "legendFormat": "Contracts",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gocore_node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gocore_contracts_created\")\n  |> filter(fn: (r) => r.host == \"${gocore_address}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Block Difficulty",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 12 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "gocore_block_difficulty",
     "legendFormat": "Difficulty",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gocore_node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gocore_block_difficulty\")\n  |> filter(fn: (r) => r.host == \"${gocore_address}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Block Size",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "gocore_block_size_bytes",
     "legendFormat": "Token Transfers",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gocore_node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gocore_block_size_bytes\")\n  |> filter(fn: (r) => r.host == \"${gocore_address}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Energy Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 5, "x": 5, "y": 13 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "gocore_block_energy_used",
     "legendFormat": "Token Transfers",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gocore_node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gocore_block_energy_used\")\n  |> filter(fn: (r) => r.host == \"${gocore_address}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Block Nonce",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 13 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "gocore_block_nonce / 1000000000000000000",
     "legendFormat": "Nonce",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gocore_node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gocore_block_nonce\")\n  |> filter(fn: (r) => r.host == \"${gocore_address}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> map(fn: (r) => ({\n      r with\n      _value: r._value / uint(v: 1000000000000000000)\n    })\n  )"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 4, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "gocore_load_time",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gocore_node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gocore_load_time\")\n  |> filter(fn: (r) => r.host == \"${gocore_address}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "title": "Pending Transactions",
   "type": "graph",
   "gridPos": { "h": 6, "w": 20, "x": 4, "y": 19 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "gocore_pending_transactions",
     "legendFormat": "transactions",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gocore_node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gocore_pending_transactions\")\n  |> filter(fn: (r) => r.host == \"${gocore_address}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 25 },
   "options": {
    "content": "<p align=\"center\" style=\"font-size:30pt\">Today Totals</p>"
   }
  },
  {
   "title": "Transactions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "locale" }
   ],
   "targets": [
    {
     "expr": "gocore_block_transactions",
     "legendFormat": "Transactions",
     "query": "from(bucket: \"my-bucket\")\n  |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n  |> filter(fn: (r) => r[\"_measurement\"] == \"gocore_node\")\n  |> filter(fn: (r) => r[\"_field\"] == \"gocore_pending_transactions\")\n  |> filter(fn: (r) => r.host == \"${gocore_address}\")\n  |> aggregateWindow(every: v.windowPeriod, fn: last, createEmpty: false)\n  |> yield(name: \"last\")"
    }
   ]
  }
 ]
}