apiVersion: 1

datasources:
  - name: InfluxDB_v2_Flux
    type: influxdb
    editable: true
    url: ${INFLUXDB_URL}
    secureJsonData:
      token: ${INFLUXDB_TOKEN}
    isDefault: true
    jsonData:
      version: Flux
      organization: ${INFLUXDB_ORG}
      defaultBucket: ${INFLUXDB_BUCKET}
      tlsSkipVerify: true